In [64]:
import numpy as np 
#Function for inputting a matrix.
def mat_input(m,n):
    mat=np.zeros((m,n),dtype=float)
    for i in range(m):
        for j in range(n):
            mat[i][j]=int(input())
    return mat
#Function for Computing Row Reduced Echelon Form
def row_reduced_echelon(M,m,n):
    i=0
    for j in range(n):
        flag =0
        if i<m and M[i][j]==0:
                flag = 1
                for k in range(i+1,m):
                    if M[k][j]!=0:
                        swap(M,i,k)
                        flag=0
                        break
        if flag==0 and i<m:
               # print (i)
                M[i]= M[i]/M[i][j]
                #print ("==============")
                #print (M)
                for l in range(m):
                    if i !=l:
                        M[l] = M[l]-M[i]*M[l][j];
                        #print ("==================")
                        #print (M)
                i=i+1    
    
    if M[0][0]==0:
        for k in range(1,n):
                    if M[0][k]!=0:
                        M=swap_col(M,0,k)
                        break;
                                    
    return M  
#Swapping Rows
def swap(M,i,k):
    #print(i,k)
    l=M[i].copy();
    #print(l)
    M[i]=M[k];
   # print(M[i])
    M[k]=l;
    #print(M[k])
#Swapping Columns
def swap_col(M,i,k):
    #print(M)
    N=np.transpose(M);
   # print(N)
   # print(i,k)
    swap(N,i,k)
   # print(N)
    return np.transpose(N)



m = int(input("Enter number of rows for your matrix: "))
n = int(input("Enter number of columns for your matrix: "))
in_mat = mat_input(m,n)
print(in_mat.copy())
print("==============")
k = row_reduced_echelon(in_mat.copy(),m,n)
print(k)

Enter number of rows for your matrix: 4
Enter number of columns for your matrix: 2
0
0
0
0
1
0
1
1
[[0. 0.]
 [0. 0.]
 [1. 0.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [63]:
#Determining whether the inverse exists
#if exists, find inverse
if m== n:
  print("The input matrix is a square matrix")
  determinant=np.linalg.det(in_mat)
  print("determinant=", determinant)
  if determinant ==0:
    print("Inverse does not exist. The entered matrix is a Singular matrix")
  else:
    print("Inverse exists")
    I=np.identity(m)
    print(I)
    print(in_mat)
    aug=np.concatenate((in_mat,I),axis=1)
    print(aug)
    inverse_mtx=row_reduced_echelon(aug,m,n+m)
    print(inverse_mtx)
    print("The augmented matrix after row reduction is:", inverse_mtx)
    print("Therefore, the inverse matrix is:", inverse_mtx[...,n:])

else:
  print("No. of rows and columns are unequal. Inverse cannot be determined")


The input matrix is a square matrix
determinant= -2.0000000000000004
Inverse exists
[[1. 0.]
 [0. 1.]]
[[1. 2.]
 [3. 4.]]
[[1. 2. 1. 0.]
 [3. 4. 0. 1.]]
[[ 1.   0.  -2.   1. ]
 [-0.   1.   1.5 -0.5]]
The augmented matrix after row reduction is: [[ 1.   0.  -2.   1. ]
 [-0.   1.   1.5 -0.5]]
Therefore, the inverse matrix is: [[-2.   1. ]
 [ 1.5 -0.5]]
